# Generated by Django 5.0.7 on 2024-07-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='activity',
            field=models.CharField(max_length=50),
        ),
    ]
