# Generated by Django 5.0.7 on 2024-07-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_alter_todomodel_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='activity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
