# Generated by Django 5.0.7 on 2024-07-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_alter_todomodel_activity_alter_todomodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='activity',
            field=models.CharField(default='Fales', max_length=50),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='name',
            field=models.CharField(default='Fales', max_length=100),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='subject',
            field=models.CharField(default='Fales', max_length=50),
        ),
    ]
