# Generated by Django 5.0.7 on 2024-07-11 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_alter_todomodel_activity_alter_todomodel_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoModel',
        ),
    ]
