# Generated by Django 5.0.7 on 2024-07-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='complete',
            field=models.BooleanField(default='False'),
        ),
    ]
